### ISSUE TITLE
restart not working (Mac launchd)

### ISSUE THREAD

**Issue by ifunlisted** [gismo141/homebridge-server#59] opened 2018-07-31 17:59 UTC
I'm using...
"restart" : "launchctl unload ~/Library/LaunchAgents/com.homebridge.server.plist && launchctl load ~/Library/LaunchAgents/com.homebridge.server.plist"
...for restart in config.json, but it doesn't seem to be working. It does work in Terminal.

When I use the Restart button on the web ui, it appears to unload fine, but then never reloads.

I'm running on a Mac, using launchd

**Comment by mbbeaubi** [comment] 2018-12-03 02:30
Faced the same issue. I think the problem is with the usage of the node.js exec method in the code. Not a node.js expert, but this method seems to terminate the underlying command execution when the node.js server shuts down. So the first part of the command executes, shuts down the node.js server, then the second part doesn't execute.

Figured out a simple workaround. Create a script, restart.sh with contents:

`#!/bin/sh

launchctl unload ~/Library/LaunchAgents/com.homebridge.server.plist && launchctl load ~/Library/LaunchAgents/com.homebridge.server.plist
`

Then set the restart command to ~/.homebridge/restart.sh &

**Comment by gismo141** [comment] 2018-12-29 13:25
Thats true, I'll change the wiki accordingly.

**Comment by gismo141** [comment] 2018-12-29 13:51
Fixed by https://github.com/gismo141/homebridge-server/wiki/Usage#launchd

**Closed as completed by gismo141** 2018-12-29 13:51 UTC
